Algoritmo "Exercicio 52"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Caio
// Data atual  : 11/04/2023
Var
// Seção de Declarações das variáveis 
   contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 100 ate 110 passo 1 faca
escreval(contadora)
fimpara

Fimalgoritmo

52) Escreva um algoritmo para imprimir os 10 primeiros números inteiros
maiores que 100.